CruGlobal/ab_service_custom_reports

handlers/report.js
reports/templates/well-invoice.ejs
reports/templates/well-receipt.ejs
reports/well-invoice.js
reports/well-receipt.js

Per Johnny's suggestions switch to a single handler for our custom reports. 
```
GET /report/:key
```
After definitions change will depreciate existing routes:
```
GET /custom_reports/well-invoice
GET /custom_reports/well-receipt
```
Related PR:
digi-serve/ab_service_api_sails#12
digi-serve/ab_service_config#7

Common report handler

---

handlers/report.js
reports/team-monthly.js
reports/templates/team-monthly.ejs

https://github.com/digi-serve/ns_app/issues/34

+Add team monthly report

---

reports/_utils.js
reports/balance-report.js
reports/balance-sheet.js
reports/team-monthly.js
reports/templates/team-monthly.ejs

https://github.com/digi-serve/ns_app/issues/34#issuecomment-1227981002
https://github.com/digi-serve/ab_service_custom_reports/pull/4#pullrequestreview-1081659200

*Fix display number digits and put a common function to a shared file

---

reports/team-monthly.js

https://github.com/digi-serve/ns_app/issues/34#issuecomment-1255739546

+Add generate "All of My RCs" feature to the report 

---

reports/team-monthly.js
reports/templates/team-monthly.ejs

https://github.com/digi-serve/ns_app/issues/34#issuecomment-1255739546

*Fix display all the RCs in a team in a report

---

reports/balance-report.js

https://github.com/digi-serve/ns_app/issues/163

*Fix pull data with user scope

---

reports/_utils.js
reports/balance-report.js
reports/team-monthly.js

https://github.com/digi-serve/ns_app/issues/120

*Use model-get service to pull data

---

reports/income-vs-expense.js

https://github.com/digi-serve/ns_app/issues/183

*Fix default FY period option of the Incode vs Expense report

---

reports/abReportBalance.js
reports/balance-report.js
reports/balance-sheet.js

Add in Active Fiscal Month
https://github.com/digi-serve/ns_app/issues/180

Month filter fix

---

reports/abReportBalance.js
reports/balance-report.js
reports/balance-sheet.js

include active month as option
Turns out It helps to push the change to master

fix: update filter

---

reports/local-income-expense.js
reports/templates/local-income-expense.ejs

https://github.com/digi-serve/ns_app/issues/234

Improve Local Income vs Expense report

---

reports/local-income-expense.js
reports/templates/local-income-expense.ejs

https://github.com/digi-serve/ns_app/issues/234

[Fix]Options&Decimal

---

reports/local-income-expense.js

https://github.com/digi-serve/ns_app/issues/234

[Fix]Options-Month

---

reports/budget-vs-expense.js
reports/templates/budget-vs-expense.ejs

https://github.com/digi-serve/ns_app/issues/83

[Fix] Bug and Option Budget VS Expense Report

---

reports/budget-vs-expense.js

https://github.com/digi-serve/ns_app/issues/83

[Fix]Populate and First Page Load

---

reports/budget-vs-expense.js

https://github.com/digi-serve/ns_app/issues/83

[Fix]glue and rules filter

---

reports/budget-vs-expense.js

https://github.com/digi-serve/ns_app/issues/83

[Fix]Populate From True To Array

---

reports/local-income-expense.js
reports/scripts/local-income-expense.js
reports/templates/local-income-expense.ejs

https://github.com/digi-serve/ns_app/issues/294

Allow users to select multiple options in the ministry team and rc

---

reports/local-income-expense.js
reports/scripts/local-income-expense.js

https://github.com/digi-serve/ns_app/issues/295
https://github.com/digi-serve/ns_app/issues/293

Add the MCC option and update report values calculating

---

reports/budget-vs-expense.js
reports/local-income-expense.js
reports/scripts/local-income-expense.js

https://github.com/digi-serve/ns_app/issues/330
https://github.com/digi-serve/ns_app/issues/342
- Apply all RC list for Core users in the Budget vs Actual report
- Allow Core Finance users to see all teams data the Local Income vs Expense report
- Remove the MCC option in the Local Income vs Expense report

Fix option issue of CORE user to reports

---

reports/balance-report.js

https://github.com/digi-serve/ns_app/issues/329
- Allow Core Finance users to see all teams in the RC Balances report

Allow Core Finance users to see all teams in the RC Balances report

---

reports/budget-vs-expense.js

- Add more filter to pull Team and RC data

+Add more filter to pull Team and RC data

---

reports/balance-report.js
reports/budget-vs-expense.js

https://github.com/digi-serve/ns_app/issues/342
- *Fix undefined reference issue

*Fix undefined reference issue

---

reports/scripts/_team-rc-fy.js
reports/scripts/local-income-expense.js
reports/scripts/team-monthly.js
reports/team-monthly.js
reports/templates/local-income-expense.ejs
reports/templates/team-monthly.ejs

- Add `Ministry Team` option
- Apply multiselect to `RC` option
- Allow Core Finance users to see all teams data

Update options in the team monthly report

---

reports/scripts/_team-rc-fy.js

https://github.com/digi-serve/ns_app/issues/331
- Fix Core Finance users can see all ministry teams in the team monthly report

*Fix Core Finance users can see all ministry teams in the team monthly report

---

reports/scripts/_loading-cursor.js
reports/scripts/_team-rc-fy.js
reports/templates/balance-report.ejs
reports/templates/balance-sheet.ejs

https://github.com/digi-serve/ns_app/issues/66
- Add progress loading the the balance sheet report

Add progress loading the the balance sheet report

---

reports/budget-vs-expense.js
reports/scripts/_team-rc-fy.js

https://github.com/digi-serve/ns_app/issues/369
- FY Period in descending order
- Rename budget vs expense report

*FY Period in descending order & Rename budget vs expense report

---

reports/income-vs-expense.js
reports/templates/income-vs-expense.ejs

https://github.com/digi-serve/ns_app/issues/370
- Update FY Period of I&E Report

*Update FY Period of I&E Report

---

reports/income-vs-expense.js
reports/templates/income-vs-expense.ejs

https://github.com/digi-serve/ns_app/issues/370
- Fix options of the income & expense report

*Fix options of the income & expense report

---

reports/balance-report.js

https://github.com/digi-serve/ns_app/issues/363
- Fix MCC options for core finance users in the RC balance report

*Fix MCC options for core finance users

---

reports/balance-report.js

- *Fix filter of balances data

*Fix filter of balances data

---

reports/balance-report.js
reports/templates/balance-report.ejs

- Improve performance of RC Balance report

*Improve performance of RC Balance report

---

reports/templates/balance-report.ejs

*Fix select all MCC option

---

reports/scripts/_team-rc-fy.js

https://github.com/digi-serve/ns_app/issues/408
- Filter RC options by selected teams

*Filter RC by selected teams

---

reports/scripts/_team-rc-fy.js
reports/scripts/local-income-expense.js

https://github.com/digi-serve/ns_app/issues/408\#issuecomment-2017508440
- Pull all of RC  data to the option in the local income expense report

*Populate RC options in the local income expense report

---

reports/team-monthly.js

- Prevent duplicate filter condition & pull data without any filter
Add code to clean up filter conditions of the report. It should have the test case for this already.

*Prevent duplicate filter condition & pull data without any filter

---

reports/local-income-expense.js

https://github.com/digi-serve/ns_app/issues/431
- Add filter to RC data in the local income expense report

Add filter to RC data in the local income expense report

---

reports/scripts/_team-rc-fy.js
reports/scripts/local-income-expense.js

https://github.com/digi-serve/ns_app/issues/431
- Fix RC options in local income & expense report

*Fix RC options in local income & expense report

---

reports/income-vs-expense.js

https://github.com/digi-serve/ns_app/issues/452
- Fix value calculation of Income & Expense report

*Fix value calculation of Income & Expense report

---

reports/balance-report.js
reports/templates/balance-report.ejs

https://github.com/digi-serve/ns_app/issues/36
- Add "Team" & "QX" options to the RC Balance report

+Add "Team" & "QX" options to the RC Balance report

---

reports/balance-report.js

https://github.com/digi-serve/ns_app/issues/468
- Scope QX options for the user

*Limit QX options for the user

---

reports/income-vs-expense.js

https://github.com/digi-serve/ns_app/issues/452
- Fix calculate values of the income & expense report

*Fix calculate value of the income & expense report

---

reports/income-vs-expense.js

https://github.com/digi-serve/ns_app/issues/452
- Fix pull data with start FY period

*Fix pull data with start FY period

---

reports/income-vs-expense.js

https://github.com/digi-serve/ns_app/issues/370
- Fix pull data when select start FY M01 option

*Fix pull data when select start FY M01 option

---

reports/_utils.js
reports/income-vs-expense.js
reports/local-income-expense.js
reports/scripts/_team-rc-fy.js
reports/scripts/local-income-expense.js
reports/scripts/team-monthly.js
reports/team-monthly.js
reports/templates/income-vs-expense.ejs

https://github.com/digi-serve/ns_app/issues/432
- Add Calendar month label to options

Add Calendar month label to options

---

reports/balance-report.js
reports/budget-vs-expense.js
reports/team-monthly.js

https://github.com/digi-serve/ns_app/issues/503
- Filter inactive RCs

*Filter inactive RCs

---

reports/budget-vs-expense.js
reports/templates/budget-vs-expense.ejs

- Add expense information of each project in Budget & Expense report

Add expense information of each project in Budget & Expense report

---

reports/templates/budget-vs-expense.ejs

Fix undefined object

---

reports/templates/budget-vs-expense.ejs

- Update pull expense detail from Report Items object

Update pull expense detail from Report Items object

---

reports/budget-vs-expense.js

-Clean code

---

reports/templates/budget-vs-expense.ejs

- Fix toggle UI expense info panel

*Fix toggle UI expense info panel

---

reports/budget-vs-expense.js
reports/templates/budget-vs-expense.ejs

- Roll back pull expense info from the query

*Roll back pull expense info from the query

---

reports/scripts/_team-rc-fy.js

https://github.com/digi-serve/ns_app/issues/474
- Fix refresh data when select a option

*Fix refresh data when select a option

---

handlers/report.js
reports/fcf-due-dates.js
reports/templates/fcf-due-dates.ejs

- Create a due dates report to replace current Access Database report.

Create due dates report for FCF.

---

reports/fcf-due-dates.js

- Fix issue where person does not have visa attached to profile.

BugFix: Make sure person has visa attached before lookup

---

reports/fcf-due-dates.js

Check item exisits

---

reports/fcf-due-dates.js
reports/templates/fcf-due-dates.ejs

increase limit so we do not miss any people

---

reports/templates/budget-vs-expense.ejs

https://github.com/digi-serve/ns_app/issues/524
- Fix display total of RC in Budget & Actual report

*Fix display total of RC in Budget & Actual report
